// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTWWUXgz8eXqSSyQHPtqxMOiQL65lL1I',
    appId: '1:970718060323:web:4207bfb2c437b1f9c47696',
    messagingSenderId: '970718060323',
    projectId: 'contacts-d2fdf',
    authDomain: 'contacts-d2fdf.firebaseapp.com',
    storageBucket: 'contacts-d2fdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywBeLLHyZWavGsICSAcvpgda_-KGwQxQ',
    appId: '1:970718060323:android:94d25a00c05bf2b7c47696',
    messagingSenderId: '970718060323',
    projectId: 'contacts-d2fdf',
    storageBucket: 'contacts-d2fdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeznp_b16m1Vpm-x7mM1reMFp3T4SMFjA',
    appId: '1:970718060323:ios:19048131b747f23bc47696',
    messagingSenderId: '970718060323',
    projectId: 'contacts-d2fdf',
    storageBucket: 'contacts-d2fdf.appspot.com',
    iosClientId: '970718060323-r0fjo8g0tmpoktes97if11mq92lm89vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeznp_b16m1Vpm-x7mM1reMFp3T4SMFjA',
    appId: '1:970718060323:ios:19048131b747f23bc47696',
    messagingSenderId: '970718060323',
    projectId: 'contacts-d2fdf',
    storageBucket: 'contacts-d2fdf.appspot.com',
    iosClientId: '970718060323-r0fjo8g0tmpoktes97if11mq92lm89vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.contact',
  );
}
